version: "3.7"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server
  redis-server:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    ports:
      - target: 6379
        published: 6379
volumes:
  cache:
    driver: local
